id: P010647
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS19177
  title: བདུད་རྩི་སྨན་གྱི་མདོ་ཆོག
  author: ''
  volumes:
    51d649aad9134166bbc157d111ced563:
      image_group_id: I8LS19179
      title: ''
      volume_number: 1
      total_pages: 484
      base_file: v001.txt
